### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by markst** [nahive/doppelganger-swift#1]
Not sure if this is xcode 8 related. 
But can't seem to get this to build.

I'm importing library into my class:
`import Doppelganger_Swift`

However I can't install when referencing `NIArrayDiffUtility`.
![image](https://cloud.githubusercontent.com/assets/274318/18742868/bd63fd92-80f9-11e6-8b76-52fee18dab17.png)

**Comment by markst** [comment]
I think this is due to `NIArrayDiffUtility` needing to be defined as `public`.
`public class NIArrayDiffUtility`

**Comment by nahive** [comment]
Please download updated (0.2.0) files manually as currently I can't update cocoapods repo due to technical difficulties.

**Comment by markst** [comment]
This still seems to be an issue with `0.2.0`
